import { readFileSync } from 'node:fs';
import { describe, it, expect } from 'vitest';
import { compileMethodology, evaluateMethodology, type FactorInput } from '@/lib/methodology/expression';
import { parseMetricSchema, validateValues, type Expression } from '@/lib/methodology/schema';
import { buildMethodologyForm } from '@/lib/methodology/form';
import { Decimal } from '@/lib/methodology/decimal';
const seeds = [...readFileSync('supabase/migrations/0014_project_platform_samples.sql', 'utf8').matchAll(/\$metric\$(.*?)\$metric\$/gs)].map(m => JSON.parse(m[1]));
function simple(expression: Expression = { field: 'x' }) { return { schema_version: 1, fields: [{ id: 'x', label: { vi: 'X' }, type: 'decimal', scope: 'observation', unit: '1', required: true }], factor_requirements: [], calculations: [{ id: 'result', unit: '1', aggregation: 'sum', expression }] }; }
function run(expression: Expression, x = '2') { return evaluateMethodology(simple(expression), {}, [{ record_key: 'a', values: { x } }], []).results.result.value; }
describe('SQL seed contract and generated forms', () => {
    it.each([0, 1, 2, 3])('compiles actual seed %s and exposes all fields', index => { const s = parseMetricSchema(seeds[index]), form = buildMethodologyForm(s); expect(compileMethodology(s).order).toHaveLength(s.calculations.length); expect(form.baseline.length + form.observation.length).toBe(s.fields.length); expect(form.baseline[0].required).toBe(true); });
    it('renders boolean, enum labels, units and aliases without project-specific code', () => { expect(buildMethodologyForm(seeds[1]).observation.find(f => f.id === 'meter_checked')?.control).toBe('checkbox'); const e = buildMethodologyForm(seeds[3]).observation.find(f => f.id === 'equipment_type')!; expect(e.control).toBe('select'); expect(e.options[0]).toEqual({ value: 'flare', label: 'Đốt khí' }); expect(buildMethodologyForm(seeds[0]).observation.find(f => f.id === 'area_ha')?.accepted_units).toEqual(['ha', 'm2']); });
});
describe('schema rejection and canonical validation', () => {
    it.each([null, undefined, 'eval', '', 1])('rejects invalid op %s (including PostgreSQL regression op=null)', op => { expect(() => compileMethodology(simple({ op, args: [{ constant: 1 }, { constant: 2 }] } as Expression))).toThrow(); });
    it('rejects embedded JS and extra AST keys', () => { expect(() => compileMethodology(simple({ constant: 1, js: 'process.exit()' } as Expression))).toThrow(); });
    it('rejects duplicate field ids', () => { const s = simple(); s.fields.push(s.fields[0]); expect(() => parseMetricSchema(s)).toThrow(/Duplicate/); });
    it.each(['banana', null])('rejects field type %s', type => { const s = simple(); Object.assign(s.fields[0], { type }); expect(() => parseMetricSchema(s)).toThrow(); });
    it('rejects inverted bounds', () => { const s = simple(); Object.assign(s.fields[0], { validation: { minimum: 2, maximum: 1 } }); expect(() => parseMetricSchema(s)).toThrow(/bounds/); });
    it('rejects enum duplicate code and missing options', () => { const s = simple(); Object.assign(s.fields[0], { type: 'enum', options: [{ value: 'a', label: { vi: 'A' } }, { value: 'a', label: { vi: 'B' } }] }); expect(() => parseMetricSchema(s)).toThrow(/enum/); });
    it('requires canonical strings and scale, bounds, correct scope', () => { const s = parseMetricSchema(seeds[0]); expect(validateValues(s, { baseline_stock_tc_ha: 1 }, 'baseline')).toHaveLength(1); expect(validateValues(s, { baseline_stock_tc_ha: '1.00001' }, 'baseline')).toHaveLength(1); expect(validateValues(s, { baseline_stock_tc_ha: '-1' }, 'baseline')).toHaveLength(1); expect(validateValues(s, { baseline_stock_tc_ha: '1', area_ha: '1' }, 'baseline')).toHaveLength(1); });
    it('checks required_if in values and form, without hiding fields', () => { const s = simple(); s.fields.push({ id: 'flag', label: { vi: 'Flag' }, type: 'boolean', scope: 'observation', unit: '1', required: true }); Object.assign(s.fields[0], { required: false, required_if: { field: 'flag', equals: true } }); const parsed = parseMetricSchema(s); expect(validateValues(parsed, { flag: false }, 'observation')).toEqual([]); expect(validateValues(parsed, { flag: true }, 'observation')[0].field).toBe('x'); expect(buildMethodologyForm(s, 'vi', { flag: true }).observation.find(f => f.id === 'x')?.required).toBe(true); });
    it('rejects conditional cycle and wrong conditional value', () => { const s = simple(); s.fields.push({ ...s.fields[0], id: 'y' }); Object.assign(s.fields[0], { required_if: { field: 'y', equals: '1' } }); Object.assign(s.fields[1], { required_if: { field: 'x', equals: '1' } }); expect(() => parseMetricSchema(s)).toThrow(/cycle/); Object.assign(s.fields[0], { required_if: { field: 'y', equals: true } }); expect(() => parseMetricSchema(s)).toThrow(/condition/); });
    it('rejects impossible ISO dates and invalid enum codes', () => { const s = simple(); Object.assign(s.fields[0], { type: 'date' }); expect(validateValues(parseMetricSchema(s), { x: '2025-02-29' }, 'observation')).toHaveLength(1); expect(validateValues(parseMetricSchema(seeds[3]), { digester_code: 'd', biogas_m3: '1', methane_fraction: '0.5', equipment_type: 'Máy phát' }, 'observation')[0].message).toContain('enum'); });
    it('rejects non-finite constants', () => { expect(() => run({ constant: Infinity })).toThrow(); expect(() => run({ constant: NaN })).toThrow(); });
});
describe('AST dependencies, unit algebra and limits', () => {
    it('sorts forward references topologically and uses per-record calculations before aggregate', () => { const s = simple({ calculation: 'first' }); s.calculations.push({ id: 'first', unit: '1', aggregation: 'sum', expression: { field: 'x' } }); expect(compileMethodology(s).order).toEqual(['first', 'result']); const r = evaluateMethodology(s, {}, [{ record_key: 'b', values: { x: '3' } }, { record_key: 'a', values: { x: '2' } }], []); expect(r.results.result.value).toBe('5.0000'); expect(r.trace.records[0].record_key).toBe('a'); expect(r.trace.records[0].calculations.result.nodes[0].value).toBe('2'); });
    it('detects indirect and self cycles', () => { const s = simple({ calculation: 'other' }); s.calculations.push({ id: 'other', unit: '1', aggregation: 'sum', expression: { calculation: 'result' } }); expect(() => compileMethodology(s)).toThrow(/cycle/); expect(() => compileMethodology(simple({ calculation: 'result' }))).toThrow(/cycle/); });
    it.each([{ field: 'missing' }, { baseline: 'x' }, { factor: 'missing' }, { calculation: 'missing' }] as Expression[])('rejects missing/wrong scope reference %j', expression => expect(() => compileMethodology(simple(expression))).toThrow(/reference|Unknown/));
    it('rejects arithmetic on text', () => { const s = simple(); s.fields[0].type = 'text'; expect(() => compileMethodology(s)).toThrow(/non-numeric/); });
    it('rejects addition with incompatible units and declared output mismatch', () => { const s = simple({ op: 'add', args: [{ field: 'x' }, { constant: 1 }] }); s.fields[0].unit = 'ha'; expect(() => compileMethodology(s)).toThrow(/units/); expect(() => compileMethodology({ ...simple(), calculations: [{ ...simple().calculations[0], unit: 'ha' }] })).toThrow(/unit mismatch/); });
    it('does not implicitly equate scaled units ha and m2', () => { const s = simple({ op: 'add', args: [{ field: 'x' }, { field: 'y' }] }); s.fields[0].unit = 'ha'; s.fields.push({ ...s.fields[0], id: 'y', unit: 'm2' }); expect(() => compileMethodology(s)).toThrow(/units/); });
    it('rejects division by zero', () => expect(() => run({ op: 'divide', args: [{ field: 'x' }, { constant: 0 }] })).toThrow(/zero/));
    it('enforces binary arity', () => expect(() => compileMethodology(simple({ op: 'divide', args: [{ constant: 1 }, { constant: 2 }, { constant: 3 }] }))).toThrow());
    it('rejects depth above 24', () => { let expression: Expression = { field: 'x' }; for (let i = 0; i < 25; i++)
        expression = { op: 'add', args: [expression, { constant: 1 }] }; expect(() => compileMethodology(simple(expression))).toThrow(/depth/); });
    it('rejects cyclic JS object before recursive parsing', () => { const expression: Expression = { op: 'add', args: [] }; expression.args = [expression, { constant: 1 }]; expect(() => compileMethodology(simple(expression))).toThrow(/Cyclic/); });
    it('rejects oversized schema object', () => { const s = simple(); Object.assign(s, { huge: Array(20001).fill(1) }); expect(() => compileMethodology(s)).toThrow(/resource/); });
    it('enforces overall evaluation operation limit', () => { const observations = Array.from({ length: 10000 }, (_, i) => ({ record_key: String(i), values: { x: '1' } })); expect(() => evaluateMethodology(simple({ op: 'add', args: Array.from({ length: 8 }, () => ({ field: 'x' })) }), {}, observations, [])).toThrow(/Operation limit/); });
    it('limits observation count and rejects duplicates', () => { expect(() => evaluateMethodology(simple(), {}, Array(10001).fill({ record_key: 'a', values: { x: '1' } }), [])).toThrow(/count/); expect(() => evaluateMethodology(simple(), {}, Array(2).fill({ record_key: 'a', values: { x: '1' } }), [])).toThrow(/duplicate/); });
    it('checks pow literal integer, negative exponent and dimensions', () => { expect(run({ op: 'pow', args: [{ field: 'x' }, { constant: -2 }] })).toBe('0.2500'); expect(() => run({ op: 'pow', args: [{ field: 'x' }, { constant: 0.5 }] })).toThrow(/integer/); expect(() => run({ op: 'pow', args: [{ field: 'x' }, { constant: 33 }] })).toThrow(/integer/); const s = simple({ op: 'pow', args: [{ field: 'x' }, { constant: 2 }] }); s.fields[0].unit = 'ha'; s.calculations[0].unit = 'ha^2'; expect(compileMethodology(s).order).toEqual(['result']); });
    it('fails on excessive decimal magnitude rather than infinity', () => { const s = simple({ op: 'pow', args: [{ field: 'x' }, { constant: 32 }] }); expect(() => evaluateMethodology(s, {}, [{ record_key: 'a', values: { x: '9'.repeat(99) } }], [])).toThrow(/magnitude/); });
});
describe('decimal numerical expectations and traces', () => {
    it.each([
        ['add', '0.1', '0.2', '0.3000'], ['subtract', '1', '0.9', '0.1000'], ['multiply', '1.2', '3', '3.6000'], ['divide', '1', '3', '0.3333'], ['min', '-2', '3', '-2.0000'], ['max', '-2', '3', '3.0000'],
    ] as const)('%s %s %s = %s', (op, a, b, expected) => expect(run({ op, args: [{ field: 'x' }, { constant: Number(b) }] }, a)).toBe(expected));
    it.each([['1.23445', '1.2344'], ['1.23455', '1.2346'], ['-1.23445', '-1.2344'], ['-1.23455', '-1.2346']])('half-even %s => %s', (a, b) => expect(Decimal.parse(a).fixed(4)).toBe(b));
    it('keeps >53-bit decimal values exact and division has 28 significant digits', () => { expect(Decimal.parse('9007199254740993').add(Decimal.parse('0.1')).toString()).toBe('9007199254740993.1'); expect(Decimal.parse(1).div(Decimal.parse(3)).toString()).toBe('0.3333333333333333333333333333'); expect(Decimal.parse(2).div(Decimal.parse(3)).toString()).toBe('0.6666666666666666666666666667'); });
    it.each([['sum', '6.0000'], ['mean', '2.0000'], ['min', '1.0000'], ['max', '3.0000']])('aggregates %s', (aggregation, expected) => { const s = simple(); s.calculations[0].aggregation = aggregation; const r = evaluateMethodology(s, {}, [1, 2, 3].map(x => ({ record_key: String(x), values: { x: String(x) } })), []); expect(r.results.result.value).toBe(expected); expect(r.trace.aggregation[0].inputs).toEqual(['1', '2', '3']); });
    it('selects exactly one scoped factor, captures source, rejects ambiguity/missing/wrong unit', () => { const s = simple({ op: 'multiply', args: [{ field: 'x' }, { factor: 'f' }] }); Object.assign(s, { factor_requirements: [{ key: 'f', unit: '1', scope_selectors: ['x'] }] }); const factors: FactorInput[] = [{ key: 'f', unit: '1', scope: { x: '2' }, source: 'sourceA', value: '3' }, { key: 'f', unit: '1', scope: { x: '4' }, source: 'sourceB', value: '5' }]; const r = evaluateMethodology(s, {}, [{ record_key: 'a', values: { x: '2' } }], factors); expect(r.results.result.value).toBe('6.0000'); expect(r.trace.records[0].factors[0].source).toBe('sourceA'); for (const bad of [[], [...factors, factors[0]], [{ ...factors[0], unit: 'ha' }]])
        expect(() => evaluateMethodology(s, {}, [{ record_key: 'a', values: { x: '2' } }], bad)).toThrow(/factor/); });
});
