import { readFileSync } from 'node:fs';
import { describe, it, expect } from 'vitest';
import { canonicalNumber, excelDate, parseCSV, previewCSV, previewTable, previewExcel, prepareImportRecords, type Cell } from '@/lib/monitoring/import';
const seeds = [...readFileSync('supabase/migrations/0014_project_platform_samples.sql', 'utf8').matchAll(/\$metric\$(.*?)\$metric\$/gs)].map(m => JSON.parse(m[1]));
const header = 'record_key,observed_on,plot_code,area_ha,stock_tc_ha';
const good = header + '\na,2026-01-01,P1,2,12';
describe('CSV grammar', () => {
    it('handles BOM, escaped quotes, quoted delimiter/newline and CRLF', () => { const t = parseCSV('\uFEFFa,b\r\n"x,""y""\r\nz",2\r\n'); expect(t.errors).toEqual([]); expect(t.rows[0]).toEqual({ row: 2, cells: ['x,"y"\r\nz', '2'] }); });
    it.each(['a,b\n"unterminated,2', 'a,b\na"bad,2', 'a,b\n"ok"bad,2'])('rejects malformed quoting %s', csv => expect(parseCSV(csv).errors).not.toHaveLength(0));
    it('detects missing and extra cells with row/column', () => { const t = parseCSV('a,b\n1\n1,2,3'); expect(t.errors.map(e => [e.row, e.column])).toEqual([[2, 2], [3, 3]]); });
    it('preserves trailing empty cell and supports CR and tabs', () => { expect(parseCSV('a\tb\r1\t\r', '\t').rows[0].cells).toEqual(['1', '']); });
    it('rejects blank file, data-less file and resource excess', () => { expect(previewCSV(seeds[0], '').valid).toBe(false); expect(previewCSV(seeds[0], header).valid).toBe(false); expect(() => parseCSV('x'.repeat(10 * 1024 * 1024 + 1))).toThrow(/size/); });
});
describe('mapping, locale, units and validation preview', () => {
    it('produces canonical records and pure commit payload', () => { const p = previewCSV(seeds[0], good); expect(p.errors).toEqual([]); expect(p.valid).toBe(true); expect(p.records[0].metric_values).toEqual({ plot_code: 'P1', area_ha: '2', stock_tc_ha: '12' }); expect(prepareImportRecords(seeds[0], parseCSV(good))[0]).toEqual({ record_key: 'a', observed_on: '2026-01-01', values: { plot_code: 'P1', area_ha: '2', stock_tc_ha: '12' }, raw_input: p.records[0].raw_input, source_row: 2 }); });
    it('maps aliases with explicit m2 to ha and locale separators', () => { const csv = 'record_key;observed_on;Mã ô đo;Diện tích ô đo;Trữ lượng carbon đo được\na;2026-01-01;P1;20.000,00;12,50'; const p = previewCSV(seeds[0], csv, { delimiter: ';', decimalSeparator: ',', thousandsSeparator: '.', columns: { 'Diện tích ô đo': { field: 'area_ha', unit: 'm2' } } }); expect(p.errors).toEqual([]); expect(p.records[0].metric_values.area_ha).toBe('2'); expect(p.records[0].metric_values.stock_tc_ha).toBe('12.50'); });
    it('accepts comma decimal quoted under comma CSV delimiter', () => { const p = previewCSV(seeds[0], header + '\na,2026-01-01,P1,"2,5",12', { decimalSeparator: ',' }); expect(p.valid).toBe(true); expect(p.records[0].metric_values.area_ha).toBe('2.5'); });
    it.each(['1,23,456', '1.2.3', '1e3', 'NaN', 'Infinity', '1,000.00x'])('rejects malformed number %s', raw => expect(() => canonicalNumber(raw, { thousandsSeparator: ',' })).toThrow());
    it('does not guess ambiguous separators and rejects identical settings', () => { expect(() => canonicalNumber('1,5')).toThrow(); expect(canonicalNumber('1 234,5', { decimalSeparator: ',', thousandsSeparator: ' ' })).toBe('1234.5'); expect(() => canonicalNumber('1', { decimalSeparator: ',', thousandsSeparator: ',' })).toThrow(/differ/); });
    it('rejects unknown/missing columns and prevents preparation', () => { const text = good.replace('area_ha', 'mystery'); const p = previewCSV(seeds[0], text); expect(p.errors.some(e => e.message === 'Unknown column')).toBe(true); expect(p.errors.some(e => e.field === 'area_ha' && e.message === 'Missing required column')).toBe(true); expect(() => prepareImportRecords(seeds[0], parseCSV(text))).toThrow(/invalid/); });
    it('rejects duplicate header and alias targeting same field', () => { expect(previewCSV(seeds[0], good.replace('area_ha', 'plot_code')).errors.some(e => e.message === 'Duplicate header')).toBe(true); expect(previewCSV(seeds[0], good.replace('stock_tc_ha', 'Diện tích ô đo')).errors.some(e => e.message === 'Duplicate mapped field')).toBe(true); });
    it('rejects ambiguous alias and typo in explicit mapping', () => { const s = structuredClone(seeds[0]); s.fields[3].import.aliases.push('area_ha'); expect(previewCSV(s, good).errors.some(e => e.message === 'Ambiguous alias')).toBe(true); expect(previewCSV(seeds[0], good, { columns: { typo: { field: 'area_ha' } } }).valid).toBe(false); });
    it('rejects unknown units and unaccepted conversions', () => { for (const unit of ['acre', 'kWh'])
        expect(previewCSV(seeds[0], good, { columns: { area_ha: { field: 'area_ha', unit } } }).valid).toBe(false); });
    it('does not silently round excess scale from conversion', () => { expect(previewCSV(seeds[0], good.replace(',2,12', ',1.1,12'), { columns: { area_ha: { field: 'area_ha', unit: 'm2' } } }).errors.some(e => e.message === 'Exceeds precision scale')).toBe(true); });
    it('reports blank required cell, invalid date and duplicate record key', () => { const p = previewCSV(seeds[0], header + '\na,2026-02-30,P1,,12\na,2026-01-01,P2,1,13'); expect(p.errors.some(e => e.row === 2 && e.field === 'observed_on')).toBe(true); expect(p.errors.some(e => e.row === 2 && e.field === 'area_ha')).toBe(true); expect(p.errors.some(e => e.row === 3 && e.message === 'Duplicate record_key')).toBe(true); });
    it('imports baseline separately and energy boolean/biogas enum values', () => { expect(previewCSV(seeds[0], 'baseline_stock_tc_ha\n10', { scope: 'baseline' }).baselineRows[0].values).toEqual({ baseline_stock_tc_ha: '10' }); expect(previewCSV(seeds[1], 'record_key,observed_on,meter_code,electricity_mwh,meter_checked\na,2026-01-01,M1,100,false').records[0].metric_values.meter_checked).toBe(false); expect(previewCSV(seeds[3], 'record_key,observed_on,digester_code,biogas_m3,methane_fraction,equipment_type\na,2026-01-01,D1,100,0.5,flare').valid).toBe(true); });
    it('retains source physical row after multiline cell', () => { const p = previewCSV(seeds[0], header + '\na,2026-01-01,"plot\nA",1,12\nb,2026-01-01,P2,2,13'); expect(p.records.map(r => r.source_row)).toEqual([2, 4]); });
    it.each(['=SUM(1)', '+cmd', '@SUM(1)', '-cmd'])('rejects formula-like CSV %s', formula => expect(previewCSV(seeds[0], good.replace('P1', formula)).valid).toBe(false));
});
describe('Excel adapter boundary and dates (no actual XLSX parser)', () => {
    it.each([[1, '1900', '1900-01-01'], [59, '1900', '1900-02-28'], [61, '1900', '1900-03-01'], [0, '1904', '1904-01-01']] as const)('serial %s system %s => %s', (serial, system, expected) => expect(excelDate(serial, system)).toBe(expected));
    it.each([60, -1, 1.5, Infinity])('rejects invalid/fictitious serial %s', serial => expect(() => excelDate(serial)).toThrow());
    it('rejects missing adapter explicitly', async () => { await expect(previewExcel(seeds[0], new Uint8Array(), 'Sheet1', undefined)).rejects.toThrow(/not installed/); });
    it('converts typed Excel serial and rejects formula cells, without consuming cached value', async () => { const table = parseCSV(good); table.rows[0].cells[1] = { kind: 'excel-date', serial: 46023 }; expect(previewTable(seeds[0], table).records[0].observed_on).toBe('2026-01-01'); table.rows[0].cells[3] = { kind: 'formula', formula: '1+1' }; const parser = { parse: async () => table }; const p = await previewExcel(seeds[0], new Uint8Array(), 'Sheet1', parser); expect(p.errors.some(e => e.message.includes('Formula cells'))).toBe(true); });
    it('rejects Excel error cells', () => { const t = parseCSV(good); t.rows[0].cells[3] = { kind: 'error', message: '#DIV/0!' } as Cell; expect(previewTable(seeds[0], t).errors.some(e => e.message === '#DIV/0!')).toBe(true); });
});
